
package om.getOucuInfo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GetOucuInfo", targetNamespace = "http://tempuri.org//GetOucuInfo", wsdlLocation = "http://csintra6-test.open.ac.uk/SAMSWebServices/SAMSValidationWS/GetOucuInfo.asmx?WSDL")
public class GetOucuInfo_Service
    extends Service
{

    private final static URL GETOUCUINFO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(om.getOucuInfo.GetOucuInfo_Service.class.getName());
    private final static String WSDLUrl="http://csintra6-test.open.ac.uk/SAMSWebServices/SAMSValidationWS/GetOucuInfo.asmx?WSDL";

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = om.getOucuInfo.GetOucuInfo_Service.class.getResource(".");
            url = new URL(baseUrl, WSDLUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: " + url + ", retrying as a local file");
            logger.warning(e.getMessage());
        }
        GETOUCUINFO_WSDL_LOCATION = url;
    }

    public GetOucuInfo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetOucuInfo_Service() {
        super(GETOUCUINFO_WSDL_LOCATION, new QName("http://tempuri.org//GetOucuInfo", "GetOucuInfo"));
    }

    /**
     * 
     * @return
     *     returns GetOucuInfoSoap
     */
    @WebEndpoint(name = "GetOucuInfoSoap")
    public GetOucuInfoSoap getGetOucuInfoSoap() {
        return super.getPort(new QName("http://tempuri.org//GetOucuInfo", "GetOucuInfoSoap"), GetOucuInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetOucuInfoSoap
     */
    @WebEndpoint(name = "GetOucuInfoSoap")
    public GetOucuInfoSoap getGetOucuInfoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org//GetOucuInfo", "GetOucuInfoSoap"), GetOucuInfoSoap.class, features);
    }

}
