
package om.getOucuInfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetOucuInfoSoap", targetNamespace = "http://tempuri.org//GetOucuInfo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetOucuInfoSoap {


    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.getoucuinfo.OucuInfo
     */
    @WebMethod(operationName = "GetOucuInfo", action = "http://tempuri.org//GetOucuInfo/GetOucuInfo")
    @WebResult(name = "GetOucuInfoResult", targetNamespace = "http://tempuri.org//GetOucuInfo")
    @RequestWrapper(localName = "GetOucuInfo", targetNamespace = "http://tempuri.org//GetOucuInfo", className = "org.tempuri.getoucuinfo.GetOucuInfo")
    @ResponseWrapper(localName = "GetOucuInfoResponse", targetNamespace = "http://tempuri.org//GetOucuInfo", className = "org.tempuri.getoucuinfo.GetOucuInfoResponse")
    public OucuInfo getOucuInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org//GetOucuInfo")
        GetOucuInfoRequest request);

}
